In [22]:
import numpy as np

In [5]:
x=np.array([3,1,2])
print(x)
type(x)

[3 1 2]


numpy.ndarray

In [6]:
a=[1,2,"a","b"]
b=np.array([1,2,"a","b"])
print(a)
print(b)

[1, 2, 'a', 'b']
['1' '2' 'a' 'b']


In [ ]:
# c=[[1],[2,3],[4,5,6]]
# d=np.array([[1],[2,3],[4,5,6]])
# print(c)
# print(d)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [12]:
list1=[1,2,3]
list2=[4,5,6]
list1+list2

[1, 2, 3, 4, 5, 6]

In [13]:
ndarray1=np.array([1,2,3])
ndarray2=np.array([4,5,6])
ndarray1+ndarray2

array([5, 7, 9])

In [14]:
list3=[1,3,5]
list4=[2,4]
list3+list4

[1, 3, 5, 2, 4]

In [15]:
# ndarray3=np.array([1,2,3])
# ndarray4=np.array([4,5])
# ndarray2+ndarray4

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [16]:
x=np.array([1.0,2.0,3.0])
y=np.array([2.0,4.0,6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [17]:
A=np.array([1.0,2.0,3.0])
print(A.shape)

(3,)


In [19]:
print(A.dtype)

float64


In [28]:
ndar1 = np.array([[1, 2],
                  [3, 4]])
ndar2 = np.array([[1, 2],
                  [3, 4]])
print(np.dot(ndar1, ndar2))

[[ 7 10]
 [15 22]]


In [29]:
ndar1 = np.array([[1, 2],
                  [3, 4]])
ndar2 = np.array([[1, 2],
                  [3, 4]])
print(np.matmul(ndar1,ndar2))

[[ 7 10]
 [15 22]]


In [30]:
ndar1 = np.array([1, 2, 3])
ndar2 = np.array([[6, 3],
                  [5, 2],
                  [4, 1]])
print(np.matmul(ndar1, ndar2))

[28 10]


In [31]:
ndar1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
ndar2 = np.array([[6, 3],
                  [5, 2],
                  [4, 1]])
print(np.matmul(ndar1, ndar2))

[[28 10]
 [73 28]]


In [32]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [33]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
print(np.full((2,3),5))

[[5 5 5]
 [5 5 5]]


In [35]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
ndarr=np.array([[6,3],[5,2],[4,1]])
ndarr.flatten()

array([6, 3, 5, 2, 4, 1])

In [39]:
ndarr=np.array([[6,3],[5,2],[4,1]])
print(ndarr.shape)
ndarr.reshape(2,3)

(3, 2)


array([[6, 3, 5],
       [2, 4, 1]])

In [41]:
print(np.arange(5))
print(np.arange(5,10))
print(np.arange(5,10,2))

[0 1 2 3 4]
[5 6 7 8 9]
[5 7 9]


In [44]:
# np.random.randint(5) # 0~4까지의 난수
np.random.randint(5,10) # 5~9까지의 난수
# np.random.randint(5,size=(2,4)) # 0~4까지의 2x4 행렬 형태의 난수

7

In [45]:
np.random.rand(5)

array([0.4039219 , 0.52941394, 0.51604063, 0.0825889 , 0.37769543])

In [46]:
np.random.rand(2,3)

array([[0.21217859, 0.56670266, 0.1436628 ],
       [0.8870738 , 0.1551445 , 0.21726053]])

In [47]:
rng=np.random.default_rng()
rng.random()

0.013743142184760804

In [48]:
rng.integers(0, 10, (2, 4))

array([[6, 9, 1, 3],
       [6, 7, 6, 6]])

In [49]:
ndarr = np.array([[6, 3],
                  [5, 2],
                  [4, 1]])
ndarr > 4

array([[ True, False],
       [ True, False],
       [False, False]])

In [50]:
ndarr = np.array([[6, 3],
                  [5, 2],
                  [4, 1]])
ndarr[ndarr > 4]

array([6, 5])