In [1]:
print("Hello World")

Hello World


In [3]:
a=1

In [5]:
a

1

In [7]:
b=[1,2,3,4,5]
b

[1, 2, 3, 4, 5]

In [8]:
b*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [3]:
import numpy as np
x=np.array([3,1,2])
print(x)
type(x)
print([3,1,2,"a"])
y=np.array([1,2,3,"a"])
print(y)

[3 1 2]
[3, 1, 2, 'a']
['1' '2' '3' 'a']


In [18]:
c=[[1],[1,2]]
# d=np.array([[1],[1,2]])
d=np.array([[2,1],[1,2]])

In [19]:
for x,y in d:
  print(x,y)

2 1
1 2


In [23]:
%ls

 C ����̺��� �������� �̸��� �����ϴ�.
 ���� �Ϸ� ��ȣ: 68DB-64E1

 c:\Users\dawoo\Desktop\SF7\python\24.12.13 ���͸�

24-12-13(��)  ���� 11:44    <DIR>          .
24-12-13(��)  ���� 11:34    <DIR>          ..
24-12-13(��)  ���� 10:38           243,834 1.png
24-12-13(��)  ���� 09:32    <DIR>          output
24-12-13(��)  ���� 12:27             4,437 practice1.ipynb
24-12-13(��)  ���� 09:28               230 practice1.py
24-12-13(��)  ���� 09:32               135 practice2.py
24-12-13(��)  ���� 10:17               672 practice3.py
24-12-13(��)  ���� 10:42               626 practice4.py
24-12-13(��)  ���� 10:49               133 practice5.py
24-12-13(��)  ���� 10:53               313 practice6.py
24-12-13(��)  ���� 09:03               372 programmers_codingtest1.py
24-12-13(��)  ���� 09:10               175 programmers_codingtest2.py
24-12-13(��)  ���� 10:24               478 test1.py
              11�� ����             251,405 ����Ʈ
               3�� ���͸�  313,474,613,248 ����Ʈ ����


In [25]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [27]:
list1=[1,3,5]
list2=[2,4,8]
list1+list2

[1, 3, 5, 2, 4, 8]

In [29]:
ndarray1=np.array([1,3,5])
ndarray2=np.array([2,4,8])
ndarray1+ndarray2

array([ 3,  7, 13])

In [4]:
x=np.array([1.0,2.0,3.0])
y=np.array([2.0,4.0,6.0])
# 문자일 경우엔 불가능
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [41]:
print(x.shape) # 차원
print(d.shape)
print(x.dtype)
print(y/2.0)
x.ndim
d.ndim # 차원을 출력하는 명령어

(3,)
(2, 2)
float64
[1. 2. 3.]


2

In [5]:
x.ndim

1

In [46]:
a=np.array([[1,2],[3,4],[5,6]]) # 3행 2열열
b=np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
c=np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])
print(a.ndim)
print(a.shape)
print(b.ndim)
print(b.shape)
print(c.ndim)
print(c.shape)


2
(3, 2)
3
(3, 2, 1)
3
(3, 2, 2)


In [48]:
print(np.dot(4,2))

8


In [6]:
ndar1=np.array([1,2,3])
ndar2=np.array([4,5,6])
print(np.dot(ndar1,ndar2))

32


In [57]:
ndar1=np.array([[1,2],
                [3,4]])
ndar2=np.array([[1,2],
                [3,4]])
print(np.dot(ndar1,ndar2))

[[ 7 10]
 [15 22]]


In [59]:
ndar1=np.array([[1],
                [3]])
ndar2=np.array([[1,2]])
print(np.dot(ndar1,ndar2))

[[1 2]
 [3 6]]


In [60]:
ndar1=np.array([[1,2]])
ndar2=np.array([[1],[2]])
print(np.dot(ndar1,ndar2))

[[5]]


In [73]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [65]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [66]:
print(np.full((2,3),5))

[[5 5 5]
 [5 5 5]]


In [67]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
ndarr=np.array([[6,3],[5,2],[4,1]])
ndarr.flatten()

array([6, 3, 5, 2, 4, 1])

In [78]:
ndarr2=np.array([[[1],[2]],[[3],[4]]])
print(ndarr2.shape)
print(ndarr2.ndim)
a=ndarr2.flatten()
print(a.ndim)
print(ndarr2)


(2, 2, 1)
3
1
[[[1]
  [2]]

 [[3]
  [4]]]


In [82]:
ndarr=np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)
ndarr.reshape(1,6)
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [93]:
np.random.randint(5, size=(2,4))

array([[1, 1, 1, 0],
       [4, 3, 1, 3]], dtype=int32)

In [84]:
np.random.rand(2,4)

array([[0.35005149, 0.10751152, 0.51841474, 0.6131384 ],
       [0.85831969, 0.10921653, 0.36963435, 0.66682234]])

In [95]:
rng=np.random.default_rng()

In [96]:
rng.random()

0.7636334762562473

In [98]:
rng.integers(0, 10, (2, 4))

array([[1, 0, 7, 6],
       [7, 7, 9, 3]])

In [108]:
ndarr=np.array([[6,3],[5,2],[4,1]])
ndarr>4

array([[ True, False],
       [ True, False],
       [False, False]])

In [109]:
ndarr[ndarr>4]

array([6, 5])

In [105]:
ndarr[ndarr>1]

array([6, 3, 5, 2, 4])

In [110]:
ndarr[ndarr<1]

array([], dtype=int64)

In [112]:
ndarr[1:]

array([[5, 2],
       [4, 1]])