In [2]:
import numpy as np

In [6]:
a=np.array([[1,2],[3,4]])
print(a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)


In [7]:
expand=np.expand_dims(a,0)
print(expand)
print(expand.shape)

[[[1 2]
  [3 4]]]
(1, 2, 2)


In [9]:
expand2=np.expand_dims(a,1)
print(expand2)
print(expand2.shape)

[[[1 2]]

 [[3 4]]]
(2, 1, 2)


In [12]:
expand3=np.expand_dims(a,2)
print(expand3)
print(expand3.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [15]:
np_ones=np.ones((1,2,1,3))
print(np_ones)
print(np_ones.shape)

[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]
(1, 2, 1, 3)


In [18]:
squeeze1=np.squeeze(np_ones)
print(squeeze1)
print(squeeze1.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [20]:
squeeze2=np.squeeze(np_ones,0)
print(squeeze2)

[[[1. 1. 1.]]

 [[1. 1. 1.]]]


In [21]:
a = [1, 2, 2, 3, 3, 3, 4, 4]
u_a = np.unique(a)
print(u_a)

[1 2 3 4]


In [25]:
a = [1, 2, 2, 3, 4, 3, 4, 3, 1]
u_a, count = np.unique(a, return_counts=True)
print(u_a, count)

[1 2 3 4] [2 2 3 2]


In [26]:
a = [1, 2, 2, 3, 4, 3, 4, 3, 1]
u_a, index = np.unique(a, return_index=True)
print(u_a, index)

[1 2 3 4] [0 1 3 4]


In [27]:
a = [1, 2, 2, 3, 4, 3, 4, 3, 1]
u_a, index, counts = np.unique(a, return_index=True, return_counts=True)
print(u_a, index, counts)

[1 2 3 4] [0 1 3 4] [2 2 3 2]


In [28]:
a = [1, 2, 2, 3, 4, 3, 4, 3, 1]
u_a, counts, index = np.unique(a, return_index=True, return_counts=True)
print(u_a, index, counts)

[1 2 3 4] [2 2 3 2] [0 1 3 4]


In [29]:
a = [1, 2, 2, 3, 4, 3, 4, 3, 1]
u_a, counts, index = np.unique(a, return_counts=True, return_index=True)
print(u_a, index, counts)

[1 2 3 4] [2 2 3 2] [0 1 3 4]


In [30]:
a = [1, 2, 2, 3, 4, 3, 4, 3, 1]
u_a, index, counts = np.unique(a, return_counts=True, return_index=True)
print(u_a, index, counts)

[1 2 3 4] [0 1 3 4] [2 2 3 2]


In [31]:
def add(a=1, b=2):
    return a, b, a+b


a, b, sum = add(2, 3)
print(a, b, sum)

2 3 5


In [44]:
a = np.array([1, 4, 2, 3])
b = np.sort(a)
print(f"a : {a}")
print(f"b : {b}")

c = np.argsort(a)
print(f"c : {c}")
print(f"cc : {a[c]}")
print(f"a 원복 : {a[c.sort()].flatten()}")
# a.sort()
# print(f"sort a : {a}")


a : [1 4 2 3]
b : [1 2 3 4]
c : [0 2 3 1]
cc : [1 2 3 4]
a 원복 : [1 4 2 3]


In [45]:
a = np.array([1, 4, 2, 3])
np.mean(a)

np.float64(2.5)

In [47]:
np.std(a)

np.float64(1.118033988749895)

In [48]:
np.var(a)

np.float64(1.25)

In [49]:
np.max(a)

np.int64(4)

In [50]:
np.min(a)

np.int64(1)

In [51]:
np.sum(a)

np.int64(10)

In [52]:
np.prod(a)

np.int64(24)

In [53]:
np.median(a)

np.float64(2.5)

In [54]:
b=np.array([1,2,3,4,5,100])
np.median(b)

np.float64(3.5)

In [59]:
c=np.array([1,2,3,4,5,100,10000])
np.median(c)

np.float64(4.0)

In [60]:
c=np.array([1,2,3,4,5,100,10000])
np.mean(c)

np.float64(1445.0)

In [61]:
import numpy as np
x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]])

In [ ]:
a=np.sort()