In [3]:
import numpy as np

In [18]:
a = np.array([1, 1, 2, 3, 4, 5, 5, 5, 5, 7, 8, 9, 10, 11, 24, 100])
arr1=np.unique(a)
print(arr1)

[  1   2   3   4   5   7   8   9  10  11  24 100]


In [8]:
max_v = np.max(arr1)
min_v = np.min(arr1)
mean_v = np.mean(arr1)
print(f"max : {max_v}, min : {min_v}, mean : {mean_v}")

max : 100, min : 1, mean : 15.333333333333334


In [9]:
sum = np.sum(arr1)
print(f"sum : {sum}")

sum : 184


In [13]:
arr2 = np.sort(a)
print(arr2)
middle=np.median(arr2)
print(middle)

[  1   1   2   3   4   5   5   5   5   7   8   9  10  11  24 100]
5.0


In [5]:
x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
print(x)

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]


In [54]:
print(x[:2,:2])

[[  0   1]
 [-99   6]]


In [47]:
print(np.max(x[::,1:2]))
print(np.min(x[::,1:2]))
print(np.mean(x[::,1:2]))

11
1
6.0


In [49]:
print(np.max(x,axis=0)[0])
print(np.min(x,axis=0)[0])
print(np.mean(x,axis=0)[0])

0
-99
-66.0


In [48]:
print(np.sum(x[2:]))

-273


In [42]:
argsort = np.argsort(a)
print(f"내림차순 : {a[argsort[::-1]]}")

내림차순 : [100  24  11  10   9   8   7   5   5   5   5   4   3   2   1   1]
