In [1]:
import numpy as np

In [10]:
li=np.zeros((10))
print(li)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
li[5]=1
print(li)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [13]:
array=np.arange(10,31)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [7]:
ndarr1=np.random.randint(0,100,size=(2,2))
print(ndarr1)

[[49 99]
 [37 90]]


In [9]:
ndarr2=np.random.rand(2,4)
print(ndarr2)

[[0.29608781 0.44409298 0.50619533 0.79010821]
 [0.44545853 0.11413944 0.74533274 0.43165148]]


In [21]:
rng=np.random.default_rng(1) # seed 값 아무 값이나 넣어도 크게 다르지 않다
an4_2=rng.integers(0,100,(2,2))
print(an4_2) # 특정 seed가 들어가게되면 정해진 값들이 순서대로 출력됨

[[47 51]
 [75 95]]
