In [2]:
import numpy as np

In [55]:
rng=np.random.default_rng(100)

In [56]:
ndarr1 = rng.integers(0, 100, size=(2, 2))
print(ndarr1)
sum = 0
for i in range(len(ndarr1)):
    for j in range(len(ndarr1[i])):
        sum += ndarr1[i][j]

print(sum)

[[76 83]
 [12 59]]
230


In [82]:
arr1=np.arange(35,75)
# print(arr1)
arr2=arr1.reshape(10,4)
print(arr2)

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]


In [63]:
print(arr2[::-1])

[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]


In [125]:
print(arr2, "\n")
sub_array = np.array([i[2:] for i in arr2[1:9]])
print(sub_array)

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]] 

[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [134]:
sub_array2=np.array([i[-1] for i in arr2])
print(sub_array2)
sub_array3=sub_array2.reshape(10,1)
print(sub_array3)



[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]


In [127]:
print(sub_array3[::-1])

[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]


In [129]:
rng=np.random.default_rng(3)

In [133]:
li1=rng.integers(1,51,size=(5,6))
print(li1)
li2=np.array(li1[li1%2==0])
print(f"짝수만 출력 : {li2}")


[[48 38 17 44 20  6]
 [30 43 33 20 46 24]
 [20  8 11 35 40 15]
 [32 44  8 14 27 29]
 [20 20  7 31 47 10]]
짝수만 출력 : [48 38 44 20  6 30 20 46 24 20  8 40 32 44  8 14 20 20 10]
